
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 20 17:17:05 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACE = 4;
  public static final int CONST = 5;
  public static final int CASE = 23;
  public static final int NOTEQUAL = 41;
  public static final int GREATER = 42;
  public static final int CONTINUE = 18;
  public static final int MINUS = 36;
  public static final int FOR = 26;
  public static final int OBRACE = 3;
  public static final int CHARACTER = 51;
  public static final int OBRACKET = 9;
  public static final int SEMICOLON = 7;
  public static final int AND = 34;
  public static final int CBRACKET = 10;
  public static final int OR = 35;
  public static final int BOOL = 53;
  public static final int QMARK = 25;
  public static final int COMMA = 8;
  public static final int LESSEREQUAL = 45;
  public static final int INC = 32;
  public static final int DIV = 48;
  public static final int PLUS = 46;
  public static final int LESSER = 44;
  public static final int ASSIGN = 6;
  public static final int IF = 15;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 40;
  public static final int CPAREN = 14;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MUL = 47;
  public static final int NUMBER = 52;
  public static final int MOD = 49;
  public static final int IDENT = 50;
  public static final int BREAK = 17;
  public static final int VOID = 12;
  public static final int SWITCH = 22;
  public static final int GREATEREQUAL = 43;
  public static final int FOREACH = 29;
  public static final int COLON = 24;
  public static final int ELSE = 16;
  public static final int SKIP = 31;
  public static final int OPAREN = 13;
  public static final int ENUM = 11;
  public static final int READ = 20;
  public static final int GOTO = 30;
  public static final int WHILE = 27;
  public static final int PROG = 2;
  public static final int DEC = 33;
  public static final int LENGTH = 39;
  public static final int PRINT = 21;
  public static final int DO = 28;
}

